// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: mathv2.proto

/*
Package types is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package types

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = descriptor.ForMessage
var _ = metadata.Join

var (
	filter_MathV2_Operation_0 = &utilities.DoubleArray{Encoding: map[string]int{"oper": 0}, Base: []int{1, 1, 0}, Check: []int{0, 1, 2}}
)

func request_MathV2_Operation_0(ctx context.Context, marshaler runtime.Marshaler, client MathV2Client, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ReqMathv2
	var metadata runtime.ServerMetadata

	var (
		val string
		es  []int32
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["oper"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "oper")
	}

	es, err = runtime.EnumSlice(val, ",", Operation_value)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "oper", err)
	}

	s := make([]Operation, len(es))
	for i, v := range es {
		s[i] = Operation(v)
	}
	protoReq.Oper = s

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_MathV2_Operation_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.Operation(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_MathV2_Operation_0(ctx context.Context, marshaler runtime.Marshaler, server MathV2Server, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq ReqMathv2
	var metadata runtime.ServerMetadata

	var (
		val string
		es  []int32
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["oper"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "oper")
	}

	es, err = runtime.EnumSlice(val, ",", Operation_value)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "oper", err)
	}

	s := make([]Operation, len(es))
	for i, v := range es {
		s[i] = Operation(v)
	}
	protoReq.Oper = s

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_MathV2_Operation_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.Operation(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterMathV2HandlerServer registers the http handlers for service MathV2 to "mux".
// UnaryRPC     :call MathV2Server directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterMathV2HandlerFromEndpoint instead.
func RegisterMathV2HandlerServer(ctx context.Context, mux *runtime.ServeMux, server MathV2Server) error {

	mux.Handle("GET", pattern_MathV2_Operation_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_MathV2_Operation_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_MathV2_Operation_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterMathV2HandlerFromEndpoint is same as RegisterMathV2Handler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterMathV2HandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterMathV2Handler(ctx, mux, conn)
}

// RegisterMathV2Handler registers the http handlers for service MathV2 to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterMathV2Handler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterMathV2HandlerClient(ctx, mux, NewMathV2Client(conn))
}

// RegisterMathV2HandlerClient registers the http handlers for service MathV2
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "MathV2Client".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "MathV2Client"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "MathV2Client" to call the correct interceptors.
func RegisterMathV2HandlerClient(ctx context.Context, mux *runtime.ServeMux, client MathV2Client) error {

	mux.Handle("GET", pattern_MathV2_Operation_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_MathV2_Operation_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_MathV2_Operation_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_MathV2_Operation_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 1, 0, 4, 1, 5, 3}, []string{"grpc_study", "math", "v2", "oper"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_MathV2_Operation_0 = runtime.ForwardResponseMessage
)
