// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: tls/proto/tls.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words string `protobuf:"bytes,1,opt,name=words,proto3" json:"words,omitempty"`
}

func (x *MsgHello) Reset() {
	*x = MsgHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tls_proto_tls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgHello) ProtoMessage() {}

func (x *MsgHello) ProtoReflect() protoreflect.Message {
	mi := &file_tls_proto_tls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgHello.ProtoReflect.Descriptor instead.
func (*MsgHello) Descriptor() ([]byte, []int) {
	return file_tls_proto_tls_proto_rawDescGZIP(), []int{0}
}

func (x *MsgHello) GetWords() string {
	if x != nil {
		return x.Words
	}
	return ""
}

var File_tls_proto_tls_proto protoreflect.FileDescriptor

var file_tls_proto_tls_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6c, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x74, 0x75, 0x64,
	0x79, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x74, 0x6c, 0x73, 0x22, 0x20, 0x0a, 0x08, 0x4d, 0x73, 0x67,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x32, 0x4a, 0x0a, 0x05, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x41, 0x0a, 0x03, 0x53, 0x61, 0x79, 0x12, 0x1c, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x74, 0x6c, 0x73,
	0x2e, 0x4d, 0x73, 0x67, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x74, 0x6c, 0x73, 0x2e, 0x4d,
	0x73, 0x67, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x6f, 0x72, 0x72, 0x79, 0x46, 0x72, 0x65, 0x65, 0x35,
	0x36, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2f, 0x73, 0x72, 0x63,
	0x2f, 0x74, 0x6c, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tls_proto_tls_proto_rawDescOnce sync.Once
	file_tls_proto_tls_proto_rawDescData = file_tls_proto_tls_proto_rawDesc
)

func file_tls_proto_tls_proto_rawDescGZIP() []byte {
	file_tls_proto_tls_proto_rawDescOnce.Do(func() {
		file_tls_proto_tls_proto_rawDescData = protoimpl.X.CompressGZIP(file_tls_proto_tls_proto_rawDescData)
	})
	return file_tls_proto_tls_proto_rawDescData
}

var file_tls_proto_tls_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tls_proto_tls_proto_goTypes = []interface{}{
	(*MsgHello)(nil), // 0: grpc_study.src.tls.MsgHello
}
var file_tls_proto_tls_proto_depIdxs = []int32{
	0, // 0: grpc_study.src.tls.Hello.Say:input_type -> grpc_study.src.tls.MsgHello
	0, // 1: grpc_study.src.tls.Hello.Say:output_type -> grpc_study.src.tls.MsgHello
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tls_proto_tls_proto_init() }
func file_tls_proto_tls_proto_init() {
	if File_tls_proto_tls_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tls_proto_tls_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tls_proto_tls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tls_proto_tls_proto_goTypes,
		DependencyIndexes: file_tls_proto_tls_proto_depIdxs,
		MessageInfos:      file_tls_proto_tls_proto_msgTypes,
	}.Build()
	File_tls_proto_tls_proto = out.File
	file_tls_proto_tls_proto_rawDesc = nil
	file_tls_proto_tls_proto_goTypes = nil
	file_tls_proto_tls_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	Say(ctx context.Context, in *MsgHello, opts ...grpc.CallOption) (*MsgHello, error)
}

type helloClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloClient(cc grpc.ClientConnInterface) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Say(ctx context.Context, in *MsgHello, opts ...grpc.CallOption) (*MsgHello, error) {
	out := new(MsgHello)
	err := c.cc.Invoke(ctx, "/grpc_study.src.tls.Hello/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	Say(context.Context, *MsgHello) (*MsgHello, error)
}

// UnimplementedHelloServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (*UnimplementedHelloServer) Say(context.Context, *MsgHello) (*MsgHello, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgHello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_study.src.tls.Hello/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Say(ctx, req.(*MsgHello))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_study.src.tls.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _Hello_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tls/proto/tls.proto",
}
